variable "region" {}
variable "main_vpc_cidr" {}
variable "tags_vpc" {}
variable "tags_ig" {}
variable "subnets_cidr_zone_a" {}
variable "subnets_availability_zone_a" {}
variable "subnets_tags_zone_a" {}
variable "subnets_cidr_zone_b" {}
variable "subnets_availability_zone_b" {}
variable "subnets_tags_zone_b" {}
variable "cidr_block_route_table_public" {}
variable "tags_route_table_public" {}
variable "ami_id" {}
variable "instance_type" {}
variable "instance_tags_zone_a" {}
variable "name_sg_zone_a" {}
variable "instance_tags_zone_b" {}
variable "name_sg_zone_b" {}
variable "ingres_rules_zone_a" {}
variable "egress_rules_zone_a" {}
variable "ingres_rules_zone_b" {}
variable "egress_rules_zone_b" {}
variable "key_name" {}
variable "user_data_zone_a" {}
variable "user_data_zone_b" {}
variable "name_db_group_subnet" {}
variable "tags_db_group_subnet" {}
variable "allocated_storage" {}
variable "storage_type" {}
variable "engine" {}
variable "engine_version" {}
variable "instance_class" {}
variable "name_db" {}
variable "username" {}
variable "password" {}
variable "availability_zone" {}
variable "parameter_group_name"{}
variable "s3_bucket_web_name" {}
variable "s3_bucket_name" {}
variable "ecr_name" {}

